export const datosVideos = [
  {
    id: 0,
    category: "music",
    creador: "Whirr",
    logo: "https://yt3.ggpht.com/j4afErEK0gCo0jivbPTS4dAb5kc0dTMTBfL4_AH9ZtdWZ9hE_UV9IeRbjpaKEMmfwPVwcr2UPYY=s48-c-k-c0x00ffffff-no-rj",
    titulo: "Ease",
    visitas: "435.141 visitas",
    fecha_subida: "3 Years",
    duration: "3:30",
    thumbnail: "https://i.ytimg.com/vi/qxwNMy_gYng/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/qxwNMy_gYng?autoplay=1",
  },
  {
    id: 1,
    category: "music",
    creador: "音楽の場所♡ ❛‿❛",
    logo: "https://yt3.ggpht.com/yc6A1lZaX6nA0yb8Bd_MFrZ-GgqMkAEHwsKa6ZR4IU5atEWAZmxV9IjOXXYUGEWmknuhKO3kIA=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Gemstone2k 宝石 - HOOD GOTH, MURKYSLUGG ",
    visitas: "1093 visitas",
    fecha_subida: "1 Mes",
    duration: "3:30",
    thumbnail: "https://i3.ytimg.com/vi/JEes4BrnVeg/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/JEes4BrnVeg?autoplay=1",
  },
  {
    id: 2,
    category: "music",
    creador: "SPOOL",
    logo: "https://yt3.ggpht.com/NNXqTZi06zbxm23MXpg_oSY9D9QlR_OpsSCpWBAOXlXjNzgD0PG19QJOp1noeLJ_b-PPihS9=s800-c-k-c0x00ffffff-no-rj",
    titulo: "スプール　「sway, fadeaway」　MV",
    visitas: "435.141 visitas",
    fecha_subida: "3 años",
    duration: "3:30",
    thumbnail: "https://i3.ytimg.com/vi/Q9mhN32DWoM/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/Q9mhN32DWoM?autoplay=1",
  },
  {
    id: 3,
    category: "music",
    creador: "SlowdiveVEVO",
    logo: "https://yt3.ggpht.com/j4afErEK0gCo0jivbPTS4dAb5kc0dTMTBfL4_AH9ZtdWZ9hE_UV9IeRbjpaKEMmfwPVwcr2UPYY=s48-c-k-c0x00ffffff-no-rj",
    titulo: "When the Sun Hits (Audio)",
    visitas: "4,5 M de visitas",
    fecha_subida: "4 años",
    duration: "4:49",
    thumbnail: "https://i3.ytimg.com/vi/MKYY0IlTMw4/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/MKYY0IlTMw4?autoplay=1",
  },
  {
    id: 4,
    category: "music",
    creador: "Soda Stereo",
    logo: "https://yt3.ggpht.com/j4afErEK0gCo0jivbPTS4dAb5kc0dTMTBfL4_AH9ZtdWZ9hE_UV9IeRbjpaKEMmfwPVwcr2UPYY=s48-c-k-c0x00ffffff-no-rj",
    titulo: "Te Para 3 (MTV) - Soda Stereo",
    visitas: "201.076",
    fecha_subida: "13 años",
    duration: "4:13",
    thumbnail: "http://i3.ytimg.com/vi/yDDvp-cmw8c/hqdefault.jpg",
    url: "https://www.youtube.com/embed/yDDvp-cmw8c?autoplay=1",
  },
  {
    id: 5,
    category: "music",
    creador: "Desve 000",
    logo: "https://yt3.ggpht.com/j4afErEK0gCo0jivbPTS4dAb5kc0dTMTBfL4_AH9ZtdWZ9hE_UV9IeRbjpaKEMmfwPVwcr2UPYY=s48-c-k-c0x00ffffff-no-rj",
    titulo: "basuraastillada - buses",
    visitas: "28.755 visitas",
    fecha_subida: "2 años",
    duration: "3:59",
    thumbnail: "http://i3.ytimg.com/vi/5mXsp4t4uaw/hqdefault.jpg",
    url: "https://www.youtube.com/embed/5mXsp4t4uaw?autoplay=1",
  },

  {
    id: 6,
    category: "music",
    creador: "basuraastillada",
    logo: "https://yt3.ggpht.com/S9zvyAyGbvcsKgzXDPvORZRR1x86LWPIKxq8rxriPabUM4UstcDROZxPWoD9MqC2a8_erQp0mA=s800-c-k-c0x00ffffff-no-rj",
    titulo: "basuraastillada - herpes",
    visitas: "7129 visitas",
    fecha_subida: "1 año",
    duration: "3:35",
    thumbnail: "https://i3.ytimg.com/vi/6zZkKGSMoiE/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/6zZkKGSMoiE?autoplay=1",
  },
  {
    id: 7,
    category: "music",
    creador: "Aelst system",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJUc5kneS_EbOqyB3m-KKGrGnTB9RWSawE-w6Ugo=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Colombian Screamo Compilation",
    visitas: "3090 visitas",
    fecha_subida: "2 años",
    duration: "46:16",
    thumbnail: "http://i3.ytimg.com/vi/xYOMNan1Pzc/hqdefault.jpg",
    url: "https://www.youtube.com/embed/xYOMNan1Pzc?autoplay=1",
  },

  {
    id: 8,
    category: "music",
    creador: "Brutalismus 3000",
    logo: "https://yt3.ggpht.com/u0whTlOWol3GeH2NvH-Mb_ATEcKgoHBM9KaT3oaKXd5VXaddfIdX1hqO0kzkRtHv6S5l-cs-8g=s800-c-k-c0x00ffffff-no-nd-rj",
    titulo: "Good Girl",
    visitas: "227.150 visitas",
    fecha_subida: "2 Mes",
    duration: "3:30",
    thumbnail: "https://i3.ytimg.com/vi/HJO2ERHVRGU/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/HJO2ERHVRGU?autoplay=1",
  },

  {
    id: 9,
    category: "music",
    creador: "Karasu",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJXtXifKLyF_XofQrowkMsWCK1OoAYaBJxHgDwQk=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Shojoskip - Calmly",
    visitas: "11 M visitas",
    fecha_subida: "6 años",
    duration: "5:57",
    thumbnail: "https://i3.ytimg.com/vi/1oFGf9jc1pw/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/1oFGf9jc1pw?autoplay=1",
  },

  {
    id: 10,
    category: "vlog",
    creador: "elly belly",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJW5ekqV9HUMmcwX-mU9oaGwEac_3hcVPBrMsVkyHw=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "🌤 a (productive) day in my life: waking up at 6am, my notion setup, med school study vlog 👩🏻‍💻",
    visitas: "855.733 visitas",
    fecha_subida: "1 año",
    duration: "23:42",
    thumbnail: "https://i.ytimg.com/vi/-JRTlc5cekc/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/1xKLIDfKfVU?autoplay=1",
  },
  {
    id: 11,
    category: "vlog",
    creador: "Esther Lee",
    logo: "https://yt3.ggpht.com/4D9QhoLaltdlMQUVom0wVq3HnRL-R6V824F1KIhUB11_JUAUSYBW4L2Mpva8uhHPbIFHW4Wd=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "🌤 a (productive) day in my life: waking up at 6am, my notion setup, med school study vlog 👩🏻‍💻",
    visitas: "601.865 visitas",
    fecha_subida: "10 meses",
    duration: "15:47",
    thumbnail: "https://i.ytimg.com/vi/Lf_oflGNQrw/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/Lf_oflGNQrw?autoplay=1",
  },
  {
    id: 12,
    category: "vlog",
    creador: "Esther Lee",
    logo: "https://yt3.ggpht.com/4D9QhoLaltdlMQUVom0wVq3HnRL-R6V824F1KIhUB11_JUAUSYBW4L2Mpva8uhHPbIFHW4Wd=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Starting term 2✨ london uni vlog (+Dubai clips🌴)",
    visitas: "57.326 visitas",
    fecha_subida: "2 meses",
    duration: "15:47",
    thumbnail: "https://i.ytimg.com/vi/5UNCaPemVrI/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/5UNCaPemVrI?autoplay=1",
  },
  {
    id: 13,
    category: "vlog",
    creador: "꿀주부 Honeyjubu",
    logo: "https://yt3.ggpht.com/9j25ekQSuW4LRUv9aeWUQjD9IcsGIXYWYe6d7dxRvXMLIab_jniPTsA96ssmZYkD2IY4G0bJ=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "새벽 5시에 시작되는 부지런한 일상 / 남편도시락, 일주일 밑반찬 만들기 / 크루즈 여행",
    visitas: "503.326 visitas",
    fecha_subida: "11 marz 2023",
    duration: "20:20",
    thumbnail: "https://i.ytimg.com/vi/amtyeGUvrQg/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/amtyeGUvrQg?autoplay=1",
  },
  {
    id: 14,
    category: "vlog",
    creador: "honeybearjenn",
    logo: "https://yt3.ggpht.com/8zlOU60k9IRpcAQgkXXOcZvbthsntb7iN0xmByzdyqAnM-pUTlYJZlShfCzDxMWyrv2bS_ajIUY=s800-c-k-c0x00ffffff-no-rj",
    titulo: "art vlog ★ finals week!! as a college art student",
    visitas: "37.600 visitas",
    fecha_subida: "3 meses",
    duration: "24:07",
    thumbnail: "https://i.ytimg.com/vi/xr6lYoMewY4/sddefault.jpg",
    url: "https://www.youtube.com/embed/xr6lYoMewY4?autoplay=1",
  },
  {
    id: 15,
    category: "vlog",
    creador: "honeybearjenn",
    logo: "https://yt3.ggpht.com/8zlOU60k9IRpcAQgkXXOcZvbthsntb7iN0xmByzdyqAnM-pUTlYJZlShfCzDxMWyrv2bS_ajIUY=s800-c-k-c0x00ffffff-no-rj",
    titulo: "art vlog ★ painting, reading, crochet, slow summer days",
    visitas: "7498 visitas",
    fecha_subida: "8 meses",
    duration: "16:12",
    thumbnail: "https://i.ytimg.com/vi/JEIh2SAdLXU/sddefault.jpg",
    url: "https://www.youtube.com/embed/JEIh2SAdLXU?autoplay=1",
  },

  {
    id: 16,
    category: "vlog",
    creador: "toka",
    logo: "https://yt3.ggpht.com/wxrdOOWSMkQkzowmi9Jm81SA7Kkvi9mnnP_BDizsGnswxh_aoWQR3Z81fNtnic6XvFnJSeAsUw=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "More fun to cook yourself 🍳Record of living to eat deliciously🍚ghibli food, Japanese set meal etc.",
    visitas: "1M  visitas",
    fecha_subida: "11 meses",
    duration: "16:01",
    thumbnail: "https://i.ytimg.com/vi/t9jQtfukXaI/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/t9jQtfukXaI?autoplay=1",
  },

  {
    id: 17,
    category: "vlog",
    creador: "Maisy Leigh",
    logo: "https://yt3.ggpht.com/tFQUz-QAefb5dvILh13BY-KpzGVp3JEkMoDdOy2mMSg2oSsweAUNzCGlWsjlbh9-GPZymUvwYg=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "Life With No Distractions | Going Off-Grid, Mind Reset & Slow Living, Finding Happiness Again",
    visitas: "1M  visitas",
    fecha_subida: "12 dias",
    duration: "14:23",
    thumbnail: "https://i.ytimg.com/vi/6XvmeWogwX0/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/6XvmeWogwX0?autoplay=1",
  },

  {
    id: 18,
    category: "vlog",
    creador: "Eugenia Diaz",
    logo: "https://yt3.ggpht.com/eW_pYnzBJZamaeHzn-K0pjazhowSf_SsKXSvnmuWQrIA5i6_jWiBn_-HiCJIK6SabCeDKezcSw=s800-c-k-c0x00ffffff-no-rj",
    titulo: "6am Morning Routine Living Off Grid in the Countryside",
    visitas: "70.902 visitas",
    fecha_subida: "12 dias",
    duration: "16:35",
    thumbnail: "https://i.ytimg.com/vi/mlNgT56mARw/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/6XvmeWogwX0?autoplay=1",
  },

  {
    id: 19,
    category: "webdev",
    creador: "Fireship",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJUEZDXANi-9AD9yJzNTU1R0_cA1Brd6nLXLZaG31g=s800-c-k-c0x00ffffff-no-rj",
    titulo: "I built 10 web apps... with 10 different languages",
    visitas: "9979.600 visitas",
    fecha_subida: "11 Meses",
    duration: "14:22",
    thumbnail: "https://i.ytimg.com/vi/FQPlEnKav48/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/FQPlEnKav48?autoplay=1",
  },
  {
    id: 20,
    category: "webdev",
    creador: "Coder Coder",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJUjabKfmBe35Ftzfpqrjwtl7xYFk-tpisGTLkH3SQ=s800-c-k-c0x00ffffff-no-rj",
    titulo: "How I debug and problem-solve CSS issues",
    visitas: "6973 visitas",
    fecha_subida: "3 Meses",
    duration: "57:16",
    thumbnail: "https://i.ytimg.com/vi/kMQARvuV4HI/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/kMQARvuV4HI?autoplay=1",
  },

  {
    id: 21,
    category: "webdev",
    creador: "Coder Coder",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJUjabKfmBe35Ftzfpqrjwtl7xYFk-tpisGTLkH3SQ=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Live coding a WORDLE clone (5 hrs) | HTML Sass JS",
    visitas: "41.102 visitas",
    fecha_subida: "1 año",
    duration: "4:44",
    thumbnail: "https://i.ytimg.com/vi/PNGgQzw6PQg/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/PNGgQzw6PQg?autoplay=1",
  },

  {
    id: 22,
    category: "webdev",
    creador: "Code With Antonio",
    logo: "https://yt3.ggpht.com/O8iON5EAVx6HVKyOV5UMreLFI_0D3mJX373vTEGoNcVRpNP7Lq8swha7BSLWTiEWlZaF7a4ENW8=s800-c-k-c0x00ffffff-no-rj",
    titulo: "Live coding a WORDLE clone (5 hrs) | HTML Sass JS",
    visitas: "41.102 visitas",
    fecha_subida: "2 semanas",
    duration: "4:13:19",
    thumbnail: "https://i.ytimg.com/vi/mqUN4N2q4qY/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/mqUN4N2q4qY?autoplay=1",
  },
  {
    id: 23,
    category: "webdev",
    creador: "Fazt Code",
    logo: "https://yt3.ggpht.com/1MQimlFDJ_dRqQMZCIKv6q2-G7oIB-Vngg5-GZLaN3LTIGkXuNW79ftTWMddm0gP5xYh3EK99Q=s800-c-k-c0x00ffffff-no-rj",
    titulo:
      "Introducción a Vite, mas Deploy en Github Pages (Por si no lo vite)",
    visitas: "39.204 visitas",
    fecha_subida: "9 meses",
    duration: "20:38",
    thumbnail: "https://i.ytimg.com/vi/UX4gvort2TU/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/UX4gvort2TU?autoplay=1",
  },
  {
    id: 24,
    category: "webdev",
    creador: "Wawa Sensei",
    logo: "https://yt3.ggpht.com/bLbXs-G3tYSI_3qL_Uv83BJ14GLyj5uTx-L92fsLtNYRo-1i5anxdLPM_7I3pwG1UMw5_5HfXw=s800-c-k-c0x00ffffff-no-rj",
    titulo: "React Three Fiber Tutorial - React Spring Animations",
    visitas: "841 visitas",
    fecha_subida: "7 dias",
    duration: "7:52",
    thumbnail: "https://i.ytimg.com/vi/kOeflXVJ0cc/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/kOeflXVJ0cc?autoplay=1",
  },

  {
    id: 25,
    category: "webdev",
    creador: "Wawa Sensei",
    logo: "https://yt3.ggpht.com/bLbXs-G3tYSI_3qL_Uv83BJ14GLyj5uTx-L92fsLtNYRo-1i5anxdLPM_7I3pwG1UMw5_5HfXw=s800-c-k-c0x00ffffff-no-rj",
    titulo: "React Three Fiber Tutorial - Custom Loading Screen",
    visitas: "1304 visitas",
    fecha_subida: "2 semanas",
    duration: "8:12",
    thumbnail: "https://i.ytimg.com/vi/L12wIvuZTOY/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/kOeflXVJ0cc?autoplay=1",
  },
  {
    id: 26,
    category: "webdev",
    creador: "devaslife",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJVHNxM8mcEzUMpdHelfjR9orNS_wPAE-tUUneWJHw=s800-c-k-c0x00ffffff-no-rj",
    titulo: "How to create Ghibli-style trees with three.js",
    visitas: "162.492 visitas",
    fecha_subida: "1 mes",
    duration: "47:51",
    thumbnail: "https://i.ytimg.com/vi/IGK6eceWyU4/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/IGK6eceWyU4?autoplay=1",
  },
  {
    id: 27,
    category: "webdev",
    creador: "devaslife",
    logo: "https://yt3.ggpht.com/ytc/AL5GRJVHNxM8mcEzUMpdHelfjR9orNS_wPAE-tUUneWJHw=s800-c-k-c0x00ffffff-no-rj",
    titulo: "How to create Ghibli-style trees with three.js",
    visitas: "94.442 visitas",
    fecha_subida: "4 mes",
    duration: "1:45:14",
    thumbnail: "https://i.ytimg.com/vi/JU4VBbe23jg/maxresdefault.jpg",
    url: "https://www.youtube.com/embed/JU4VBbe23jg?autoplay=1",
  },

  // https://www.youtube.com/watch?v=JU4VBbe23jg 28
];
